spring.application.name=PeaTodoListApplication

#spring.jpa.show-sql = true

logging.level.org.springframework=DEBUG

#spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.devtools.restart.enabled=true

spring.banner.location=classpath:banner.txt
#spring.main.allow-circular-references=true

spring.profiles.active=prod