app.name=PeaTodoListApplication
app.description=${app.name} is my first web application.

spring.datasource.url=jdbc:h2:mem:pea-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=pea
spring.datasource.password=pea-test

spring.h2.console.enabled=true

