app.name=PeaTodoListApplication
app.description=${app.name} is my first web application.

spring.datasource.url=jdbc:h2:mem:pea-db
spring.datasource.username=pea
spring.datasource.password=pea

spring.h2.console.enabled=true

